corptrips/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('settlement.urls'))
]

settlement/urls.py
from django.urls import path,include
from django.contrib.auth import views
from . import views


app_name = 'settlement'

urlpatterns = [
   path('', views.home, name='home'),
   path('accounts/login/', views.login_view, name = 'login'),
   path('accounts/register/', views.register_view, name = 'register'),
 ]

settlement/models.py
from django.db import models
from django.contrib.auth.models import User

# class User

# Create your models here.

settlement/forms.py
from django import forms
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import (
    authenticate, 
    get_user_model,
     
)

User = get_user_model()

class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            user = authenticate(username=username,password=password)
            if not user:
                raise forms.ValidationError('This user doesnot exist')
            if not user.check_password(password):
                raise forms.ValidationError('Incorrect password')
            if not user.is_active:
                raise forms.ValidationError('This user is not active')
        return super(UserLoginForm,self).clean(*args,**kwargs)

class UserRegistrationForm(forms.ModelForm):
    email = forms.EmailField(label='Email Adress',widget=forms.EmailInput)
    password = forms.CharField(widget=forms.PasswordInput)
    password_confirm = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = [
            'username', 
            'email', 
            'password',
            'password_confirm'
            ]
    
    def clean(self):
        password = self.cleaned_data('password')
        password_confirm = self.cleaned_data('password_confirm')
        username = self.cleaned_data('username')
        
        if password != password_confirm:
            raise forms.ValidationError('passwords must match!')
        username_eq = User.objects.filter(username=username)
        if username_eq.exist():
            raise forms.ValidationError('username already exists!')
        return username

settlement/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, get_user_model, login, logout
from .forms import UserLoginForm, UserRegistrationForm


def login_view(request):
    next = request.GET.get('next')
    form = UserLoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        login(request,user)
        if next:
            return redirect(next)
        return redirect('/')
    
    return render(request, 'settlement/login.html', {'form':form})

def register_view(request):
    form = UserRegistrationForm(request.POST)
    return render(request, 'settlement/register.html', {'form':form})

def home(request):
    return render(request,'settlement/home.html',{})


# Create your views here.

settlement/templates/adminlte/base.html
{% load adminlte_helpers i18n %}
{% load static %}

<!DOCTYPE html>
<html>
<head>
    {% block title_outer %}
        <title>{% block title %}{{ site.name }}{% endblock %}</title>
    {% endblock %}

    {% block meta %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-COMPATIBLE" content="IE=edge">
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    {% endblock %}

    {% block stylesheets %}
        {% include 'adminlte/lib/_styles.html' %}
    {% endblock %}

    {% block extra_head %}{% endblock %}
</head>
<body class="hold-transition sidebar-mini {% block body_class %}{% block bodyclass %}{% endblock %}{% endblock %}">

{% block body %}
    <div class="wrapper">
        {% block nav_header %}
            {% include 'adminlte/lib/_main_header.html' %}
        {% endblock %}

        {% block nav_sidebar %}
            {% include 'adminlte/lib/_main_sidebar.html' %}
        {% endblock %}

        {% block content_wrapper %}
        <div class="content-wrapper">
            {% block content_header %}
                <section class="content-header">
                    {% block no_heading %}
                        <h1>
                            {% block page_name %}{% endblock %}
                            <div class="header-actions">
                                {% block page_actions %}{% endblock %}
                            </div>
                            {% block no_description %}
                            <small>{% block page_description %}{% endblock %}</small>
                            {% endblock %}
                        </h1>
                        {% block breadcrumbs %}
                            {# Breadcrumb implementation left to developers #}
                        {% endblock %}
                    {% endblock no_heading %}
                </section>
            {% endblock %}

            {% block content_outer %}
            <section class="content">
                {% block messages %}
                    {% include 'adminlte/lib/_messages.html' %}
                {% endblock %}

                {% block content_block_wrap %}
                    {% block content %}{% endblock %}
                {% endblock %}
            </section>
            {% endblock %}

        </div>
        {% endblock content_wrapper %}
        
        {% block nav_footer %}
            {% include 'adminlte/lib/_main_footer.html' %}
        {% endblock %}

    </div>
{% endblock body %}

{% block javascript %}
{% include 'adminlte/lib/_scripts.html' %}
{% endblock %}

{% block extra_js %}{% endblock %}

{% block extra_foot %}{% endblock %}
</body>
</html>

settlement/templates/adminlte/components/info_box.html
{% load humanize %}
<div class="info-box bg-{{ color }}">
    {% if not hide_icon %}
        <span class="info-box-icon"><i class="fa fa-{{ icon }}"></i></span>
    {% endif %}
    <div class="info-box-content">
        <span class="info-box-text">{{ header }}</span>
        <span class="info-box-number">{{ number }} {{ unit }}</span>
        {% if percent %}
            <div class="progress">
                <div class="progress-bar" style="width: {{ percent }}%"></div>
            </div>
            {% if how_long %}
                <span class="progress-description">
                    {{ percent }}% Increase in {{ how_long }}
                </span>
            {% endif %}
        {% endif %}
    </div><!-- /.info-box-content -->
</div><!-- /.info-box -->

settlement/templates/adminlte/example.html
{% extends 'adminlte/base.html' %}

{% block content %}
    <!-- Default box -->
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Title</h3>

            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                        title="Collapse">
                    <i class="fa fa-minus"></i></button>
                <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip"
                        title="Remove">
                    <i class="fa fa-times"></i></button>
            </div>
        </div>
        <div class="box-body">
            Start creating your amazing application!
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            Footer
        </div>
        <!-- /.box-footer-->
    </div>
    <!-- /.box -->
{% endblock %}

settlement/templates/adminlte/index.html
{% extends 'adminlte/base.html' %}

{% block content %}
your awesome content
{% endblock %}

settlement/templates/adminlte/lib/_main_footer.html
<footer class="main-footer">
        <div class="float-right d-none d-sm-block">
        {% block footer_right %}
            <b>Version</b> {% block version %}0.1 beta{% endblock %}
        {% endblock %}
    </div>

    {% block footer_left %}
    {% block legal %}
    <strong>Copyright &copy; {% now "Y" %}{% if not site %}.{% endif %}
        {% if site %}
            <a href="http://{{ site.domain }}">{{ site.name }}</a>
        {% endif %}
    </strong> All rights
    reserved.
    {% endblock %}
    {% endblock %}
</footer>

settlement/templates/adminlte/lib/_main_header.html
{% load adminlte_helpers i18n %}
{% load static %}
<nav class="main-header navbar navbar-expand navbar-white navbar-light">


    <!-- Header Navbar: style can be found in header.less -->
    {% block nav_bar %}
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/" class="nav-link">Home</a>
        </li>
        <!--<li class="nav-item d-none d-sm-inline-block"> -->
        <!--    <a href="/admin" class="nav-link">Admin</a> -->
        <!-- </li> -->
    </ul>

    {% block nav_bar_center %}
    <!-- SEARCH FORM -->
    <form class="form-inline ml-3">
        <div class="input-group input-group-sm">
            <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
            <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                    <i class="fas fa-search"></i>
                </button>
            </div>
        </div>
    </form>
    {% endblock %}

    {% block nav_custom_menu %}
    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <ul class="nav navbar-nav">
            {% block header_dropdowns %}
            <!-- Messages Dropdown Menu -->
            <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#">
                    <i class="far fa-comments fa-2x"></i>
                    <span class="badge badge-danger navbar-badge">3</span>
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <a href="#" class="dropdown-item">
                        <!-- Message Start -->
                        <div class="media">
                            <img src="{%static 'admin-lte/dist/img/user1-128x128.jpg' %}" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                            <div class="media-body">
                                <h3 class="dropdown-item-title">
                                    Brad Diesel
                                    <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                                </h3>
                                <p class="text-sm">Call me whenever you can...</p>
                                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                            </div>
                        </div>
                        <!-- Message End -->
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <!-- Message Start -->
                        <div class="media">
                            <img src="{%static 'admin-lte/dist/img/user8-128x128.jpg' %}" alt="User Avatar" class="img-size-50 img-circle mr-3">
                            <div class="media-body">
                                <h3 class="dropdown-item-title">
                                    John Pierce
                                    <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                                </h3>
                                <p class="text-sm">I got your message bro</p>
                                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                            </div>
                        </div>
                        <!-- Message End -->
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <!-- Message Start -->
                        <div class="media">
                            <img src="{%static 'admin-lte/dist/img/user3-128x128.jpg' %}" alt="User Avatar" class="img-size-50 img-circle mr-3">
                            <div class="media-body">
                                <h3 class="dropdown-item-title">
                                    Nora Silvester
                                    <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                                </h3>
                                <p class="text-sm">The subject goes here</p>
                                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                            </div>
                        </div>
                        <!-- Message End -->
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
                </div>
            </li>
            <!-- Notifications Dropdown Menu -->
            <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#">
                    <i class="far fa-bell fa-2x"></i>
                    <span class="badge badge-warning navbar-badge">15</span>
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <span class="dropdown-item dropdown-header">15 Notifications</span>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-envelope mr-2"></i> 4 new messages
                        <span class="float-right text-muted text-sm">3 mins</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-users mr-2"></i> 8 friend requests
                        <span class="float-right text-muted text-sm">12 hours</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-file mr-2"></i> 3 new reports
                        <span class="float-right text-muted text-sm">2 days</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
                </div>
            </li>
            <!-- Notifications Dropdown Menu -->
            {% block user_info %}
            {% if request.user.is_authenticated %}
            <li class="nav-item dropdown">
                    <a class="nav-link" data-toggle="dropdown" href="#">
                        <i class="far fa-user fa-2x"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                        <a href="#" class="dropdown-item">
                            <!-- Message Start -->
                            <div class="media">
                                <img src="{%avatar_url size=128 %}" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                                <div class="media-body">
                                    <h3 class="dropdown-item-title">
                                            {% firstof request.user.get_short_name request.user.get_username %}
                                        <span class="float-right text-sm text-danger"><i class="fas fa-online"></i></span>
                                    </h3>
                                    <p class="text-sm"><small>{% trans 'Member since' %} :</small></p>
                                    <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i>  <small>{{ request.user.date_joined }}</small></p>
                                </div>
                            </div>
                            <!-- Message End -->
                        </a>
                        <div class="dropdown-divider"></div>
                        <div class="dropdown-footer">
                                <a href="{% block change_password_url %}{% url 'admin:password_change' %}{% endblock %}" class="btn btn-primary btn-sm">{% trans 'Change password' %}</a>
                                <a  href="{% block logout_url %}{% logout_url %}{% endblock %}" class="btn btn-danger btn-sm">{%trans 'Sign out'%}</a>
                            </div>
                        
                    </div>
                </li>
            {% endif %}
            {% endblock user_info %}
            {% endblock header_dropdowns %}
        </ul>
    </ul>
        {% endblock nav_custom_menu %}

{% endblock %}
</nav>

settlement/templates/adminlte/lib/_main_sidebar.html
{% load adminlte_helpers %}
{%load static %}
<!-- Left side column. contains the sidebar -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
     <!-- Brand Logo -->
    {% block logo %}
        <a href="/" class="brand-link">
            <img src="{%static 'admin-lte/dist/img/AdminLTELogo.png' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
            {% block logo_text %}<span class="brand-text font-weight-light">Business Trips App </span>{% endblock %}
        </a>
    {% endblock %}
    <!-- sidebar: style can be found in sidebar.less -->
    <div class="sidebar">
  
        <!-- Sidebar user panel -->
        {% block user_panel %}
        <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{% static 'admin-lte/dist/img/user1-128x128.jpg' size=90 %}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">{% firstof request.user.get_full_name request.user.username %}</a>
        </div>
      </div>
        {% endblock %}

        {% block form %}{% endblock %}

        <!-- sidebar menu: : style can be found in sidebar.less -->
        {% block nav_links_ul %}
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            {% block nav_links_outer %}
            <li class="nav-header">{% block nav_heading %}USER NAVIGATION{% endblock %}</li>

            {% block nav_links %}
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-chart-bar"></i> 
                        <p>Dashboard</p>
                    </a>
                </li>
                <li class="nav-item has-tree-view">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-tasks"></i> 
                            <p>Pending workflows</p>
                            <p><i class="right fas fa-angle-left"></i></p>
                        </a>
                        <ul class="nav nav-treeview menu-open">
                            <li class="nav-item">
                                    <a href="#" class="nav-link">
                                        <i class="nav-icon fas fa-user"></i> My tasks
                                    </a>
                                </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-users"></i> Approvals
                            </a>
                        </li>
                    </ul>

                    </li>
                <li class="nav-item has-tree-view">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-project-diagram"></i> <p>New workflow</p>
                        <p><i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview menu-open">
                            <li class="nav-item">
                                    <a href="#" class="nav-link">
                                        <i class="nav-icon fas fa-suitcase-rolling"></i> Busines Trip
                                    </a>
                                </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-wallet"></i> Advance
                            </a>
                        </li>
                    </ul>


                </li>

                <div class="user-panel mt-3 pb-3 mb-3 d-flex"></div>
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">               
                <li class="nav-header">{% block nav_heading2 %}ADMINISTRATOR NAVIGATION{% endblock %}</li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-chart-pie"></i> 
                        <p>Reporting</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-cogs"></i> 
                        <p>Settings</p>
                    </a>
                </li>
            {% endblock nav_links %}
            {% endblock nav_links_outer %}
            </ul>
            </nav>
        {% endblock nav_links_ul %}
    </div>
    <!-- /.sidebar -->
</aside>

settlement/templates/adminlte/lib/_messages.html
{% if messages %}
    {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
        <div class="alert alert-success alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
        </div>
        {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
        <div class="alert alert-danger alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
        </div>
        {% else %}
        <div class="alert alert-info alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
        </div>
        {% endif %}
    {% endfor %}
{% endif %}

settlement/templates/adminlte/lib/_pagination.html
{% if pager and ROOT_MENU.current_menu.view_name %}
    <ul class="pagination pagination-sm no-margin pull-right">
        <li><a href="{% url ROOT_MENU.current_menu.view_name %}?page=1&{{ pager.url_params }}">&laquo;</a></li>
        {% if pager.page > 2 %}
            <li>
                <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.page|add:-2}}&{{ pager.url_params }}">
                    {{ pager.page | add:-2 }}
                </a>
            </li>
        {% endif %}
        {% if pager.page > 1 %}
            <li>
                <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.page|add:-1}}&{{ pager.url_params }}">
                    {{ pager.page | add:-1 }}
                </a>
            </li>
        {% endif %}
        <li class="active"><a href="#">{{ pager.page }}</a></li>
        {% if pager.has_next %}
            <li>
                <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.page|add:1}}&{{ pager.url_params }}">
                    {{ pager.page | add:1 }}
                </a>
            </li>
        {% endif %}
        {% if pager.has_next_two %}
            <li>
                <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.page|add:2}}&{{ pager.url_params }}">
                    {{ pager.page | add:2 }}
                </a>
            </li>
        {% endif %}
        <li>
            <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.last_page}}&{{ pager.url_params }}">
            &raquo;
            </a>
        </li>
    </ul>
{% endif %}

settlement/templates/adminlte/lib/_scripts.html
{% load static %}

{% block scripts %}
<script src="{% static 'admin-lte/plugins/jquery/jquery.min.js' %}"></script>
<script src="{% static 'admin-lte/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button);
</script>
<script src="{% static 'admin-lte/plugins/bootstrap/js/bootstrap.bundle.min.js' %} "></script>


{% block datatable_js %}{% endblock %}

<script src="{% static 'admin-lte/dist/js/adminlte.min.js' %}"></script>
<script src="{% static 'admin-lte/dist/js/demo.js' %}"></script>
{% endblock %}

settlement/templates/adminlte/lib/_styles.html
{% load static %}

{% block styles %}
<!-- Font Awesome -->
<link rel="stylesheet" href="{% static 'admin-lte/plugins/fontawesome-free/css/all.min.css' %}">
<!-- Ionicons -->
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'admin-lte/dist/css/adminlte.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'admin-lte/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
{% endblock %}

settlement/templates/adminlte/pages/edit.html
{% extends 'adminlte/base.html' %}

{% block header_tail %}
    <script type="text/javascript" charset="utf-8" src="/static/plugins/ueditor/ueditor.config.js"></script>
    <script type="text/javascript" charset="utf-8" src="/static/plugins/ueditor/ueditor.all.min.js"> </script>
    <script type="text/javascript" charset="utf-8" src="/static/plugins/ueditor/lang/zh-cn/zh-cn.js"></script>
{% endblock %}

{% block content %}
    <div class="box">
        <!-- form start -->
        <form role="form" method="post">{% csrf_token %}
            <div class="box-body">
                <div class="form-group">
                    <label for="title">标题</label>
                    <input id="title" name="title" class="form-control" value="{{ page.title }}" />
                </div>
                <div class="form-group">
                    <label>正文</label>
                    <script id="editor" type="text/plain" style="width:768px;height:500px;">{{ page.content | safe }}</script>
                </div>
            </div>
            <!-- /.box-body -->

            <div class="box-footer">
                <button type="submit" class="btn btn-primary">提交</button>
            </div>
        </form>
    </div>
    <!-- /.box -->
{% endblock %}

{% block body_tail %}
    <script>
        var ue = UE.getEditor('editor', {
            textarea: 'content',
            customstyle: [
                {
                    tag: 'img',
                    name: 'img',
                    label: '',
                    style: 'width: 100%;'
                }
            ]
        });
    </script>
{% endblock %}

settlement/templates/settlement/home.html
{% extends 'adminlte/base.html' %}

{% block title %}My App{% endblock %}
{% block content %}
    Just some example content
{% endblock %}

settlement/templates/settlement/login.html
{% load static %}
{% load widget_tweaks %}
<html>
    <head>
        <link rel="stylesheet" href="{% static 'css/settlement.css' %}">
        <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    </head>
    <body>
        
        <div class="wrapper fadeInDown">
            <div id="formContent">
              <!-- Tabs Titles -->
          
              <!-- Icon -->
              <div class="fadeIn first">
                <img src="{% static 'images/LOGO_BT.png' %}" id="icon" alt="User Icon" />  
              </div>
          
              
              <!-- Login Form -->
              <form method="POST">
                {% csrf_token %}
                
                {{form.username|append_attr:"input"|append_attr:"fadeIn Secound"|attr:"placeholder:login"}}
                {{form.password|append_attr:"input"|append_attr:"fadeIn Third"|attr:"placeholder:password"}}
             
                <input type="submit" class="fadeIn fourth" value="Submit">
              </form>
              
            {% if form.non_field_errors %}
              <ul class='form-errors'>
              {% for error in form.non_field_errors %}
                <li>{{ error }}</li>
              {% endfor %}
              </ul>
            {% endif %}


              <!-- Remind Passowrd -->
              <div id="formFooter">
                <a class="underlineHover" href="{% url 'settlement:register' %}">Don't have account? Sign in</a>
              </div>
          
            </div>
          </div>
        
        
        
        
        
        
        
        
        
        
            </body>
</html>

settlement/templates/settlement/register.html
{% load static %}
{% load widget_tweaks %}
<html>
    <head>
        <link rel="stylesheet" href="{% static 'css/settlement.css' %}">
        <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    </head>
    <body>
        
        <div class="wrapper fadeInDown">
            <div id="formContent">
              <!-- Tabs Titles -->
          
              <!-- Icon -->
              <div class="fadeIn first">
                <img src="{% static 'images/LOGO_BT.png' %}" id="icon" alt="User Icon" />  
              </div>
          
              <!-- Login Form -->
              <form method="POST">
                {% csrf_token %}
                {{form.username|append_attr:"input"|append_attr:"fadeIn Secound"|attr:"placeholder:login"}}
                {{form.email|append_attr:"input"|append_attr:"fadeIn Secound"|attr:"placeholder:email"}}
                {{form.password|append_attr:"input"|append_attr:"fadeIn Secound"|attr:"placeholder:password"}}
                {{form.password_confirm|append_attr:"input"|append_attr:"fadeIn Secound"|attr:"placeholder:confirm password"}}

                <input type="submit" class="fadeIn third" value="Create account">
              </form>
          
              <!-- Remind Passowrd -->
              <div id="formFooter">
                <a class="underlineHover" href="{% url 'settlement:login' %}">Already have an account? Log in</a>
              </div>
          
            </div>
          </div>
        
        
        
        
        
        
        
        
        
        
            </body>
</html>